options:
  external-interfaces:
    default: '{"hostname":"eth1,eth2"}'
    type: string
    description: |
       One or multiple interfaces that will provide external connectivity on
       each of the gateway nodes. Provided in form of json in a string.
  lcm-ssh-key:
    default: 'null'
    type: string
    description: Public SSH key of PLUMgrid LCM which is running PG-Tools
  mgmt-interface:
    type: string
    default: 'juju-br0'
    description: The interface connected to PLUMgrid Managment network.
  network-device-mtu:
    type: string
    default: '1580'
    description: The MTU size for interfaces managed by director.
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
